.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH SPT-COMPLETION 1  "completion " 
.SH NAME
completion \- Generate shell completions
.SH SYNOPSIS
\fBcompletion\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Generate shell completions
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
completion\-generate(1)
Print completions for a shell to stdout
.TP
completion\-help(1)
Print this message or the help of the given subcommand(s)
