.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH SPT-SECRET 1  "secret " 
.SH NAME
secret \- Manage the secret vault and OS keychain references
.SH SYNOPSIS
\fBsecret\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Manage the secret vault and OS keychain references
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
secret\-store(1)
Initialize the secret store
.TP
secret\-set(1)
Set a secret
.TP
secret\-get(1)
Get a secret (redacted unless `\-\-reveal`)
.TP
secret\-list(1)
List known secret names
.TP
secret\-rotate(1)
Rotate a secret
.TP
secret\-remove(1)
Remove a secret
.TP
secret\-doctor(1)
Run secret backend health checks
.TP
secret\-help(1)
Print this message or the help of the given subcommand(s)
.SH EXTRA
EXAMPLES:
  spt secret store init \-\-backend keychain
  spt secret set db/password \-\-prompt
  spt secret set db/password \-\-from\-env DB_PASSWORD
  spt secret set api/token \-\-from\-file ~/.tokens/api
  spt secret rotate db/password
  spt secret remove db/password
