//! Mock-TLS integration tests for `spt_observability::syslog_tls`.
//!
//! These tests drive the writer end-to-end against a `tokio-rustls` server
//! using a self-signed cert generated by `rcgen`. They exercise:
//!
//! * a successful TLS handshake → octet-counted frame delivery,
//! * a server-side disconnect followed by a second accept, asserting the
//!   writer reconnects and the second payload lands,
//! * counters move (reconnects, enqueued).
//!
//! No real network traffic is generated; the listener binds on `127.0.0.1:0`.

#![allow(clippy::unwrap_used)]

use std::path::PathBuf;
use std::sync::Arc;
use std::time::Duration;

use rustls::pki_types::{CertificateDer, PrivateKeyDer};
use rustls::{RootCertStore, ServerConfig};
use spt_core::RedactionMode;
use spt_observability::syslog_tls::{spawn_writer, SyslogTlsConfig};
use spt_state::SpoolConfig;
use tokio::io::AsyncReadExt;
use tokio::net::TcpListener;
use tokio_rustls::TlsAcceptor;

/// One-shot installer for the rustls crypto provider.
///
/// rcgen pulls aws-lc-rs and rustls also wires ring; without an explicit
/// choice the default install is ambiguous and `ClientConfig::builder()`
/// panics.
fn install_provider() {
    let _ = rustls::crypto::ring::default_provider().install_default();
}

/// Generate a self-signed cert and return (DER, PEM private key, acceptor).
fn make_tls_acceptor() -> (CertificateDer<'static>, TlsAcceptor) {
    let cert =
        rcgen::generate_simple_self_signed(vec!["127.0.0.1".into(), "localhost".into()]).unwrap();
    let der = CertificateDer::from(cert.cert.der().to_vec());
    let key = PrivateKeyDer::try_from(cert.key_pair.serialize_der()).unwrap();
    let server_cfg = ServerConfig::builder()
        .with_no_client_auth()
        .with_single_cert(vec![der.clone()], key)
        .unwrap();
    (der, TlsAcceptor::from(Arc::new(server_cfg)))
}

/// Read until we have a full octet-counted frame, then return the buffer.
async fn read_one_frame<R: AsyncReadExt + Unpin>(mut sock: R) -> Vec<u8> {
    let mut buf = Vec::new();
    let mut chunk = [0u8; 4096];
    loop {
        let n = match sock.read(&mut chunk).await {
            Ok(0) => break,
            Ok(n) => n,
            Err(_) => return buf,
        };
        buf.extend_from_slice(&chunk[..n]);
        if let Some(sp_idx) = buf.iter().position(|&b| b == b' ') {
            if let Ok(s) = std::str::from_utf8(&buf[..sp_idx]) {
                if let Ok(want) = s.parse::<usize>() {
                    if buf.len() >= sp_idx + 1 + want {
                        return buf;
                    }
                }
            }
        }
    }
    buf
}

fn make_cfg(port: u16, spool_dir: PathBuf, roots: RootCertStore) -> SyslogTlsConfig {
    SyslogTlsConfig {
        host: "127.0.0.1".into(),
        port,
        app_name: "spt".into(),
        hostname: "host".into(),
        facility: 16,
        enterprise_id: 32_473,
        roots: Some(roots),
        server_name: None,
        client_cert: None,
        client_key: None,
        allow_invalid_certs: false,
        allow_self_signed: false,
        pin_spki_sha256: Vec::new(),
        max_cert_chain_depth: None,
        spool_dir,
        spool: SpoolConfig::default(),
        timeout: Duration::from_secs(2),
        reconnect_backoff: Duration::from_millis(50),
        queue_max_records: 16,
        redact: RedactionMode::Standard,
    }
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn writer_delivers_octet_counted_frame_to_tls_server() {
    install_provider();
    let (der, acceptor) = make_tls_acceptor();
    let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
    let port = listener.local_addr().unwrap().port();

    let (tx_recv, rx_recv) = tokio::sync::oneshot::channel::<Vec<u8>>();
    let acceptor_cl = acceptor.clone();
    let server = tokio::spawn(async move {
        let (sock, _) = listener.accept().await.unwrap();
        let tls = acceptor_cl.accept(sock).await.unwrap();
        let received = read_one_frame(tls).await;
        let _ = tx_recv.send(received);
    });

    let mut roots = RootCertStore::empty();
    roots.add(der).unwrap();
    let tmp = tempfile::tempdir().unwrap();
    let cfg = make_cfg(port, tmp.path().to_path_buf(), roots);

    let (layer, handle) = spawn_writer(cfg).unwrap();
    let record = b"<134>1 2024-01-01T00:00:00.000Z host spt 1 - - mock-it".to_vec();
    layer.try_send_raw(record.clone()).unwrap();

    let received = tokio::time::timeout(Duration::from_secs(5), rx_recv)
        .await
        .expect("server timed out reading the frame")
        .unwrap();

    let header = format!("{} ", record.len());
    assert!(
        received.starts_with(header.as_bytes()),
        "length header missing; got {received:?}"
    );
    let payload_start = header.len();
    assert!(received.len() >= payload_start + record.len());
    let payload = &received[payload_start..payload_start + record.len()];
    assert_eq!(payload, record.as_slice());

    // Counters: enqueued ≥ 1, no drops.
    let snap = handle.counters().snapshot();
    assert!(snap.enqueued >= 1, "enqueued counter did not move: {snap:?}");
    assert_eq!(snap.dropped_queue_full, 0);
    assert_eq!(snap.dropped_closed, 0);
    // reconnects ≥ 1 (we always pass through `connect()` once on first start).
    assert!(
        snap.reconnects >= 1,
        "reconnect counter did not move on initial connect: {snap:?}"
    );

    drop(layer);
    drop(handle.tx);
    let _ = tokio::time::timeout(Duration::from_millis(500), handle.join).await;
    let _ = server.await;
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn writer_reconnects_after_server_drops_connection() {
    install_provider();
    let (der, acceptor) = make_tls_acceptor();
    let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
    let port = listener.local_addr().unwrap().port();

    // Two oneshot channels — one per accept.
    let (tx1, rx1) = tokio::sync::oneshot::channel::<Vec<u8>>();
    let (tx2, rx2) = tokio::sync::oneshot::channel::<Vec<u8>>();
    let acc = acceptor.clone();
    let server = tokio::spawn(async move {
        // Accept #1: handshake, immediately drop without reading.
        if let Ok((sock, _)) = listener.accept().await {
            if let Ok(tls) = acc.accept(sock).await {
                // Read one frame from the first connection so we observe the
                // initial payload, then drop the socket to force a reconnect.
                let buf = read_one_frame(tls).await;
                let _ = tx1.send(buf);
                // Stream is dropped here, closing the TLS session.
            }
        }
        // Accept #2: handshake, read one frame, send it back.
        if let Ok((sock, _)) = listener.accept().await {
            if let Ok(tls) = acc.accept(sock).await {
                let buf = read_one_frame(tls).await;
                let _ = tx2.send(buf);
            }
        }
    });

    let mut roots = RootCertStore::empty();
    roots.add(der).unwrap();
    let tmp = tempfile::tempdir().unwrap();
    let mut cfg = make_cfg(port, tmp.path().to_path_buf(), roots);
    cfg.reconnect_backoff = Duration::from_millis(20);
    cfg.timeout = Duration::from_secs(2);

    let (layer, handle) = spawn_writer(cfg).unwrap();

    let first = b"<134>1 2024-01-01T00:00:00.000Z host spt 1 - - first".to_vec();
    layer.try_send_raw(first.clone()).unwrap();
    let received_first = tokio::time::timeout(Duration::from_secs(5), rx1)
        .await
        .expect("first frame timed out")
        .unwrap();
    assert!(
        received_first
            .windows(first.len())
            .any(|w| w == first.as_slice()),
        "first frame missing payload: {received_first:?}"
    );

    // The server has dropped the socket; the writer should eventually retry,
    // pick up the next message, and reach the second accept.
    //
    // Give the writer time to notice the drop (subsequent writes fail) and
    // then enqueue a second message that triggers the reconnect path.
    tokio::time::sleep(Duration::from_millis(100)).await;
    let second = b"<134>1 2024-01-01T00:00:00.000Z host spt 1 - - second".to_vec();
    // The send may briefly fail if the queue is being drained, so try a few
    // times with a small delay.
    for _ in 0..20 {
        if layer.try_send_raw(second.clone()).is_ok() {
            break;
        }
        tokio::time::sleep(Duration::from_millis(50)).await;
    }

    let received_second = tokio::time::timeout(Duration::from_secs(8), rx2)
        .await
        .expect("second frame timed out (no reconnect?)")
        .unwrap();
    assert!(
        received_second
            .windows(second.len())
            .any(|w| w == second.as_slice()),
        "second frame missing payload: {received_second:?}"
    );

    let snap = handle.counters().snapshot();
    // We should have reconnected at least twice (initial + after drop).
    assert!(
        snap.reconnects >= 2,
        "expected reconnects ≥ 2 after server drop, got {snap:?}"
    );

    drop(layer);
    drop(handle.tx);
    let _ = tokio::time::timeout(Duration::from_secs(2), handle.join).await;
    let _ = server.await;
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn writer_with_allow_invalid_certs_against_self_signed_listener() {
    install_provider();
    let (_der, acceptor) = make_tls_acceptor();
    let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
    let port = listener.local_addr().unwrap().port();

    let (tx, rx) = tokio::sync::oneshot::channel::<Vec<u8>>();
    let server = tokio::spawn(async move {
        let (sock, _) = listener.accept().await.unwrap();
        let tls = acceptor.accept(sock).await.unwrap();
        let buf = read_one_frame(tls).await;
        let _ = tx.send(buf);
    });

    // No roots; instead allow_invalid_certs=true to exercise the dangerous
    // verifier path end-to-end.
    let tmp = tempfile::tempdir().unwrap();
    let mut cfg = make_cfg(port, tmp.path().to_path_buf(), RootCertStore::empty());
    cfg.allow_invalid_certs = true;

    let (layer, handle) = spawn_writer(cfg).unwrap();
    let record = b"<134>1 2024-01-01T00:00:00.000Z host spt 1 - - no-verify".to_vec();
    layer.try_send_raw(record.clone()).unwrap();

    let received = tokio::time::timeout(Duration::from_secs(5), rx)
        .await
        .expect("server timed out")
        .unwrap();
    let header = format!("{} ", record.len());
    assert!(received.starts_with(header.as_bytes()));

    drop(layer);
    drop(handle.tx);
    let _ = tokio::time::timeout(Duration::from_millis(500), handle.join).await;
    let _ = server.await;
}
