[package]
name = "spt-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
description = "Core types, error/exit codes, and parsers for spt."

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
humantime = { workspace = true }
humantime-serde = { workspace = true }
bytesize = { workspace = true }
regex = { workspace = true }
once_cell = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
